[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pdf-toolbox"
version = "0.2.2"
description = "Utilities for PDF operations"
requires-python = ">=3.8"
dependencies = [
  "PySide6>=6.7",
  "pillow",
  "pymupdf>=1.24",
  "python-docx",
  "pywin32>=306; sys_platform == 'win32'",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "ruff",
  "mypy",
  "pre-commit",
  "build",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
extend-ignore = ["E402"]

[tool.mypy]
ignore_missing_imports = true
exclude = ["build/"]
