[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pdf-toolbox"
version = "0.2.46"
description = "Utilities for PDF operations"
requires-python = ">=3.10"
dependencies = [
  "PySide6>=6.7",
  "pillow",
  "pymupdf>=1.24",
  "python-docx",
  "pywin32>=306; sys_platform == 'win32'",
  "platformdirs",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "ruff",
  "mypy",
  "pre-commit",
  "build",
  "coverage",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
extend-ignore = ["E402"]

[tool.mypy]
ignore_missing_imports = true
exclude = ["build/"]

[tool.coverage.run]
source = ["pdf_toolbox"]
omit = ["*/pdf_toolbox/gui.py"]

[tool.coverage.report]
show_missing = true
fail_under = 95
